### ISSUE TITLE
Tasks are not loaded, due to hard-coded table prefix

### ISSUE THREAD

**Issue by RiccSicc** [fengoffice/fengoffice#28]
application/controllers/TaskController.class.php:1041

This query:
$total_worked_subquery = " (SELECT SUM(tt.worked_time) FROM fo_timeslots tt 
			INNER JOIN fo_objects oo ON oo.id=tt.object_id
			WHERE tt.rel_object_id=o.id AND oo.trashed_by_id=0) ";

Should be:

$total_worked_subquery = " (SELECT SUM(tt.worked_time) FROM " . TABLE_PREFIX . "timeslots tt 
			INNER JOIN " . TABLE_PREFIX . "objects oo ON oo.id=tt.object_id
			WHERE tt.rel_object_id=o.id AND oo.trashed_by_id=0) ";

**Comment by MaikdW** [comment]
Tasks are not loaded, despite adjustment of the snippet above

**Comment by MaikdW** [comment]
Works not, for mee

**Comment by fenix957** [comment]
Work for me.
Thank

**Comment by rwvaldivia** [comment]
@fenix957 What exactly you do to fix it?

**Comment by RiccSicc** [comment]
This issue has been fixed since version 3.8.1.29

**Comment by Christoqh** [comment]
Hi there, i experienced the described problem above with 'tasks', 'notes' and the 'overview'. It occurred for the first time after updating from 3.7.x to 3.8x.

I'm using version 3.8.1.32 now and still have this issue (not loading content or hiding it somehow) with the other two tabs 'notes' and 'overview'.
